/* ---------------------------------------------------------------------------
user.features.js
This is the slice for all the user related global state management
------------------------------------------------------------------------------ */

import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import {
  registerUser,
  loginUser,
  logout,
  getUser,
  updateUser,
  updatePassword,
  updatePic,
} from "../services/index.services.js";

/* ---------------------------------------------------------------------------
The function to register a user
------------------------------------------------------------------------------ */

const register = createAsyncThunk(
  "users/register",
  async (userData, { rejectWithValue }) => {
    try {
      const response = await registerUser(userData);
      return response; // the response sent by the backend
    } catch (error) {
      return rejectWithValue(error.response?.data?.message || error.message);
    }
  }
);

/* ---------------------------------------------------------------------------
The function to login a user
------------------------------------------------------------------------------ */

const login = createAsyncThunk(
  "users/login",
  async (userData, { rejectWithValue }) => {
    try {
      const response = await loginUser(userData);
      return response; // the response sent by the backend
    } catch (error) {
      return rejectWithValue(error.response?.data?.message || error.message);
    }
  }
);

/* ---------------------------------------------------------------------------
The Slice
------------------------------------------------------------------------------ */

const userSlice = createSlice({
  name: "users",
  initialState: {
    user: null, // will hold the fetched data
    token: null, // will hold the access token
    status: "idle", // idle, pending, succeeded, failed
    error: null, // will hold any error message
  },
  extraReducers: (builder) => {
    /* ---------------------------------------------------------------------------
       All the cases for registering a user
    ------------------------------------------------------------------------------ */

    // the pending case
    builder.addCase(register.pending, (state) => {
      (state.status = "pending"), (state.error = null); // clear previous errors
    });

    // the success case
    builder.addCase(register.fulfilled, (state, action) => {
      const user = action.payload.user;
      const token = action.payload.accessToken; // the access token generated by the Server
      (state.status = "succeeded"), (state.data = user), (state.token = token);
      localStorage.setItem("accessToken", token); // saving the access token for authentication
    });

    // the failure case
    builder.addCase(register.rejected, (state, action) => {
      (state.status = "failed"),
        (state.error = action.payload || "An unknown error occured"),
        (state.data = null); // clear data on failure
      state.token = null;
    });

    /* ---------------------------------------------------------------------------
       All the cases for logging in a user
    ------------------------------------------------------------------------------ */

    // the pending case
    builder.addCase(login.pending, (state) => {
      (state.status = "pending"), (state.error = null); // clear previous errors
    });

    // the success case
    builder.addCase(login.fulfilled, (state, action) => {
      const user = action.payload.user;
      const token = action.payload.accessToken; // the access token generated by the Server
      (state.status = "succeeded"), (state.data = user), (state.token = token);
      localStorage.setItem("accessToken", token); // saving the access token for authentication
    });

    // the failure case
    builder.addCase(login.rejected, (state, action) => {
      (state.status = "failed"),
        (state.error = action.payload),
        (state.data = null); // clear data on failure
    });
  },
});

export { register, login };

export default userSlice.reducer;
